name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ChatGPT:
    name: ChatGPT
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Integration
        uses: kxxt/chatgpt-action@v0.3
